#!/usr/bin/python2

import math
import random
import sys

def rsaEncrypt(m, e, N, lenghN):
    lengthr = int(math.ceil(lenghN/2.0)) -2
    numberr = random.getrandbits(lengthr)
    stringr = bin(numberr)[2:]
    while lengthr != len(stringr):
        numberr = random.getrandbits(lengthr)
        stringr = bin(numberr)[2:]
    stringm = bin(m)[2:]
    if len(stringm) < lenghN/2:
        zeropadding = "0" * (lenghN/2 - len(stringm))
        stringm = zeropadding + stringm
    paddedMessage = stringr + stringm
    messageelement = int(paddedMessage, 2)
    return pow(messageelement, e, N)


if __name__ == "__main__":
    secretkeyfile = open(sys.argv[sys.argv.index("-k") + 1])
    secretkey = secretkeyfile.read().split()
    inputfile = open(sys.argv[sys.argv.index("-i") + 1])
    inputmessage = int(inputfile.read().strip())
    outputfile = open(sys.argv[sys.argv.index("-o") + 1], "w+")

    cipher = rsaEncrypt(inputmessage, int(secretkey[2]), int(secretkey[1]), int(secretkey[0]))
    outputfile.write(str(cipher))
    secretkeyfile.close()
    inputfile.close()
    outputfile.close()

